[[jobs]]
name = "Transcode Movies"
enabled = true
source_path = "test-resources/test-library"
destination_path = "/media/destination/movies"
lua_script = "test-resources/test_transcode.lua"
[jobs.variables]
EXCLUDECODEC = "h265"

[master]
web_bind_addr = "0.0.0.0:8089"
orch_bind_addr = "127.0.0.1:8245"
db_path = "sqlite.db"

[worker]
master_addr = "127.0.0.1:8245"
identifier = "test-worker"
cache_dir = "/tmp/trahl-cache"
fs_remaps = [
    { master = "/", worker = "/" }
]

[log]
level = "trace"
file = "/dev/stdout"
